### ISSUE TITLE
Thanks! And a few ideas

### ISSUE THREAD

**Issue by geckolinux** [salihmarangoz/ite8291r3-gui#1]
Thanks _very_ much for this useful GUI! I really hate the keyboard combo because it's hard to find in the dark. (The Lenovo Thinkpad method of Fn+Spacebar is a much better design!) Just a few observations and ideas.

I generally just want to turn the backlight on and off. The GUI has "Turn Off keyboard backlight", which makes sense, but it would also be nice to have a top-level menu item for "Turn ON keyboard backlight" to the default white color, without having to go into the "Mono Color" menu.

Related to this, do you have any thoughts or ideas on this issue?
https://github.com/pobrn/ite8291r3-ctl/issues/13

I would find it very useful if this GUI could also support lightbar control via the `tuxedo_keyboard` module. I find the Tuxedo Control Center too bloated and intrusive. For now I'm using two systemd services to disable the keyboard backlight and the lightbar by default on bootup:

`/etc/systemd/system/off-backlight.service` 
```
[Unit]

Description=Turn off NUC9 laptop keyboard backlight at startup

[Service]

Type=oneshot
ExecStart=ite8291r3-ctl off

[Install]

WantedBy=multi-user.target
```

`cat /etc/systemd/system/off-lightbar.service`
```
[Unit]
Description=Turn off the NUC9 lightbar at startup
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/usr/bin/bash -c "/usr/bin/echo 0 > /sys/class/leds/lightbar_rgb\:1\:status/brightness"
ExecStart=/usr/bin/bash -c "/usr/bin/echo 0 > /sys/class/leds/lightbar_rgb\:2\:status/brightness"
ExecStart=/usr/bin/bash -c "/usr/bin/echo 0 > /sys/class/leds/lightbar_rgb\:3\:status/brightness"
RemainAfterExit=true
StandardOutput=journal

[Install]
WantedBy=multi-user.target
```

I generally find the lightbar to be useless, but I can think of one practical use for it: I'm used to old Thinkpads with their status LED that indicated hard disk activity. Would it be possible to make the lightbar flash or turn on to a specific color to indicate different rates of disk I/O?

Thanks a lot!

**Comment by yuky2020** [comment]
you could insert a script in your service or use a crontab and add something like this :

```bash
disk_usage= 'iostat | grep nvme1n1 | cut -c 42-45'
if [disk_usage -gt 300]
then
  echo 20 > /sys/devices/platform/tuxedo_keyboard/leds/lightbar_rgb:2:status/brightness
  if [disk_usage -gt 900]
     then
       echo 40 > /sys/devices/platform/tuxedo_keyboard/leds/lightbar_rgb:2:statu/brightness
      fi
else 
echo 0 > /sys/devices/platform/tuxedo_keyboard/leds/lightbar_rgb:2:status/brightness
fi

if [disk_usage -gt 1500]
     then
echo 20 > /sys/devices/platform/tuxedo_keyboard/leds/lightbar_rgb:1:status/brightness
else
echo 0 > /sys/devices/platform/tuxedo_keyboard/leds/lightbar_rgb:1:status/brightnes
fi
```
for sure this as too be looped every 10 sec on smething like that

**Comment by geckolinux** [comment]
Very cool! Thanks a lot for the idea.

**Comment by salihmarangoz** [comment]
@yuky2020 That's a good idea. Maybe it would look good to map the values to plasma or inferno colormap (in matplotlib) after some gamma corrections. Or similar... Actually, after switching to Nvme SSD from HDD, I stopped worrying about I/O utilitization. Addition to that, I connected a script to udev battery events and turning off lightbar if the power adapter is disconnected. But I will add this as a recommendation into the Readme. Thanks for the suggestion.

@geckolinux I am happy that it was useful. Thanks for your feedback. I can make it "Turn On/Off" and will act as a toggle. So, this way would keep the UI smaller.

**Comment by salihmarangoz** [comment]
I have added this feature with 4c35b31 . Now it looks better, I think

**Comment by salihmarangoz** [comment]
I may add lightbar control with animation, IO utilization, mono color option, if the lightbar is detected. I will be adding this to the ToDo section.

**Comment by geckolinux** [comment]
Fantastic, thanks so much @salihmarangoz !

> after switching to Nvme SSD from HDD, I stopped worrying about I/O utilitization. Addition to that, I connected a script to udev battery events and turning off lightbar if the power adapter is disconnected. 

Yes, it's not quite as necessary as it used to be. I just tend to use it as a sign that something is going wrong with the system, with my old Thinkpad whenever I saw the disk LED flash really fast or stay on solid it would usually mean a crash or hard lockup was coming.

**Comment by geckolinux** [comment]
Thanks again for the latest improvements.
It looks like a little bit more logic needs to be added to the On/Off toggle. As I mentioned, I turn the keyboard off with a Systemd service at boot that runs `ite8291r3-ctl off` . From there, the GUI On/Off toggle doesn't work and the Fn+F6/F7 keys don't either until I first select a Mono Color in the GUI. After that it all starts working as expected, and the GUI toggle can be used interchangeably with the Fn keys.

**Comment by salihmarangoz** [comment]
Oh yes, it needs some modifications such as persistent states. I am thinking about using the ideas from https://github.com/nalim/ite8291r3-gui . If you have time I welcome pull requests. I will start updating the project after 2 or 3 weeks. But that update will be really big :)

**Comment by geckolinux** [comment]
Great, no rush! I'm a pretty bad coder, I can just barely trace my way through existing code. :confounded:  :smiley:  I really do appreciate this utility, it makes a huge difference in everyday usability.

Not specific to your GUI, but I'm still trying to figure out this keyboard backlight, it really seems to have a mind of its own. I usually leave it turned off, but it seems that if I leave the laptop untouched for a while with the screen turned off via power management and then return that the keyboard backlight turns on again. Same for resuming from suspend. But it all feels very random.

**Comment by salihmarangoz** [comment]
Yeah, suspend is a bit problem for now. **nalim** solved it by setting up systemd services and persistent state memory. I just need some time to check them. When I find time to do it, it will work across reboots and sleep/wake states.

Actually, I did a quick and dirty implementation. I hope I will find a sweet spot between implementing good features and refactoring the old code.

**Comment by geckolinux** [comment]
Ah, good to know that there are still options for improvement.
And what about the keyboard backlight turning on after simply touching the trackpad after it's been sitting for a while? I can't figure out why it does that or what controls that.

**Comment by salihmarangoz** [comment]
This may be related to sleep/awake problems. I disabled sleep features on my laptop so it works perfectly. This may be related to other modules as well, different hardwares different problems. It would be better to discuss about it after the updates.
