### ISSUE TITLE
very promising

### ISSUE THREAD

**Issue by leuchtrakete666** [salihmarangoz/ite8291r3-gui#2]
very promising project. unfortunately i dont use gnome. what you think, is it possible to get this tor run on plasma as well?

**Comment by leuchtrakete666** [comment]
you should mention to first git clone, than change in the directory and than run the commands for install.

i tried it, but it dont work for my keyboard.

i get this error:
```
Traceback (most recent call last):
  File "/home/lupo/Downloads/ite8291r3-gui/../../.local/share/ite8291r3_gui/ite_tray.py", line 201, in <module>
    ite = ite8291r3.get()
  File "/home/lupo/.local/lib/python3.9/site-packages/ite8291r3_ctl/ite8291r3.py", line 298, in get
    raise FileNotFoundError("no suitable device found")
FileNotFoundError: no suitable device found
```

i have a tuxedo book xp17 gen12. its a CLEVO PC70DS-D. 
```
lsusb -d 048d:
Bus 001 Device 002: ID 048d:8910 Integrated Technology Express, Inc. ITE Device(829x)
```

i have tuxedo-keyboard and tuxedo-keyboard-ite installed. the fn key toggle works with this.

but this option is very very limited. i have high hopes in this project.

**Comment by salihmarangoz** [comment]
This app uses ite8291r3-ctl which only supports 048d:6004 and 048d:ce00. For your device check the OpenRGB project: https://gitlab.com/CalcProgrammer1/OpenRGB/-/wikis/Clevo-Per-Key-Keyboard . Also this one https://github.com/matheusmoreira/ite-829x . If you have problems while using the device try uninstalling/disabling tuxedo-keyboard module.

**Comment by salihmarangoz** [comment]
Also thanks for your comments, I will modify installation section. Also I can add some checks if user has compatible devices.
